# Generated by Django 3.2.8 on 2022-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=1, verbose_name='User ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Username')),
                ('pwd', models.CharField(default='', max_length=100, verbose_name='pwd')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
    ]
