# Generated by Django 3.2.8 on 2022-05-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='grade',
        ),
    ]
