# Generated by Django 3.2.8 on 2022-04-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_userinfo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Username')),
                ('poster', models.CharField(default='', max_length=1000, verbose_name='Poster')),
                ('visual_layout', models.CharField(default='', max_length=100, verbose_name='Visual Layout')),
                ('poster_organization', models.FloatField(default=0.0, verbose_name='Poster Organization')),
                ('poster_content', models.FloatField(default=0.0, verbose_name='Poster Content')),
                ('written_language', models.FloatField(default=0.0, verbose_name='Written Language')),
                ('oral_presentation', models.FloatField(default=0.0, verbose_name='Oral Presentation')),
            ],
            options={
                'verbose_name': 'HeadPoster',
                'verbose_name_plural': 'HeadPoster',
            },
        ),
        migrations.CreateModel(
            name='JudgePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Username')),
                ('poster', models.CharField(default='', max_length=1000, verbose_name='Poster')),
                ('visual_layout', models.CharField(default='', max_length=100, verbose_name='Visual Layout')),
                ('poster_organization', models.FloatField(default=0.0, verbose_name='Poster Organization')),
                ('poster_content', models.FloatField(default=0.0, verbose_name='Poster Content')),
                ('written_language', models.FloatField(default=0.0, verbose_name='Written Language')),
                ('oral_presentation', models.FloatField(default=0.0, verbose_name='Oral Presentation')),
            ],
            options={
                'verbose_name': 'JudgePoster',
                'verbose_name_plural': 'JudgePoster',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterid', models.IntegerField(default=0, verbose_name='Poster ID')),
                ('title', models.CharField(default='', max_length=500, verbose_name='Title')),
                ('summary', models.CharField(default='', max_length=1000, verbose_name='Summary')),
                ('file', models.CharField(default='', max_length=1000, verbose_name='File')),
                ('major', models.CharField(default='', max_length=100, verbose_name='Major')),
                ('isGraded', models.IntegerField(default=0, verbose_name='IsGraded')),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Poster',
            },
        ),
        migrations.CreateModel(
            name='PrePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Username')),
                ('posterid', models.IntegerField(default=0, verbose_name='Poster ID')),
            ],
            options={
                'verbose_name': 'PrePoster',
                'verbose_name_plural': 'PrePoster',
            },
        ),
        migrations.CreateModel(
            name='UICerPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Username')),
                ('posterid', models.IntegerField(default=0, verbose_name='Poster ID')),
                ('luckydraw', models.CharField(default='', max_length=100, verbose_name='Lucky Draw')),
            ],
            options={
                'verbose_name': 'UICerPoster',
                'verbose_name_plural': 'UICerPoster',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(default='', max_length=100, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='', max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='', max_length=100, verbose_name='Role'),
        ),
    ]
