# Generated by Django 3.2.8 on 2022-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20220427_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='poster',
            name='voteNum',
            field=models.IntegerField(default=0, verbose_name='Vote Num'),
        ),
        migrations.AddField(
            model_name='uicerposter',
            name='voteStatus',
            field=models.IntegerField(default=0, verbose_name='Vote Status'),
        ),
    ]
