# Generated by Django 3.2.8 on 2022-05-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_userinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='posterid',
        ),
    ]
