# Generated by Django 3.2.8 on 2022-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_remove_poster_posterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='file',
            field=models.FileField(default='', max_length=1000, upload_to='', verbose_name='File'),
        ),
    ]
