# Generated by Django 3.2.8 on 2022-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0009_alter_poster_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Author'),
        ),
    ]
