# Generated by Django 3.2.8 on 2022-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0011_poster_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=500, verbose_name='Username')),
                ('postid', models.IntegerField(default=0, verbose_name='poster')),
            ],
            options={
                'verbose_name': 'VotePoster',
                'verbose_name_plural': 'VotePoster',
            },
        ),
    ]
