# Generated by Django 3.2.8 on 2022-05-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0012_voteposter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotePoster',
        ),
    ]
