# Generated by Django 3.2.8 on 2022-05-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0014_auto_20220507_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicerposter',
            name='voteStatus',
        ),
    ]
