# Generated by Django 3.2.8 on 2022-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0017_auto_20220507_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeposter',
            name='judge',
            field=models.CharField(default='', max_length=1000, verbose_name='Judge'),
        ),
    ]
