# Generated by Django 3.2.8 on 2022-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0018_judgeposter_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='isGraded',
        ),
    ]
