# Generated by Django 3.2.8 on 2022-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0019_remove_poster_isgraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeposter',
            name='average',
            field=models.FloatField(default=0.0, verbose_name='Average'),
        ),
    ]
