# Generated by Django 3.2.8 on 2022-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0020_judgeposter_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='grade',
            field=models.FloatField(default=0.0, verbose_name='Grade'),
        ),
    ]
