# Generated by Django 3.2.8 on 2022-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0021_alter_poster_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='headposter',
            name='judge',
            field=models.CharField(default='', max_length=1000, verbose_name='Judge'),
        ),
    ]
