# Generated by Django 3.2.8 on 2022-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0022_headposter_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_headjudge', models.IntegerField(default=2, verbose_name='Num Head Judges')),
                ('num_judges', models.IntegerField(default=14, verbose_name='Num Judges')),
                ('num_firstprize', models.IntegerField(default=1, verbose_name='Num First Prize')),
                ('num_secondprize', models.IntegerField(default=1, verbose_name='Num Second Prize')),
                ('num_thirdprize', models.IntegerField(default=1, verbose_name='Num Third Prize')),
            ],
            options={
                'verbose_name': 'Rules',
                'verbose_name_plural': 'Rules',
            },
        ),
    ]
