# Generated by Django 3.2.8 on 2022-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0023_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100, verbose_name='Date')),
                ('time', models.CharField(default='', max_length=100, verbose_name='Time')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conference',
            },
        ),
    ]
