# Generated by Django 3.2.8 on 2022-04-12 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 4, 12, 10, 6, 57, 994649))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2022, 4, 12, 10, 6, 57, 994668))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
